
package br.com.esec.mss.ap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SignaturePortTypeV2", targetNamespace = "http://esec.com.br/mss/ap")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SignaturePortTypeV2 {


    /**
     * 
     * @param validatePdfReq
     * @return
     *     returns br.com.esec.mss.ap.ValidateRespType
     * @throws ICPMException
     */
    @WebMethod(operationName = "ValidatePdf")
    @WebResult(name = "ValidateResp", partName = "ValidateResp")
    public ValidateRespType validatePdf(
        @WebParam(name = "ValidatePdfReq", partName = "ValidatePdfReq")
        ValidatePdfReqType validatePdfReq)
        throws ICPMException
    ;

    /**
     * 
     * @return
     *     returns br.com.esec.mss.ap.BandwidthInfoType
     * @throws ICPMException
     */
    @WebMethod(operationName = "FindBandwidthInfo")
    @WebResult(name = "BandwidthInfoType", partName = "BandwidthInfoType")
    public BandwidthInfoType findBandwidthInfo()
        throws ICPMException
    ;

    /**
     * 
     * @param signatureTemplateReq
     * @return
     *     returns br.com.esec.mss.ap.SignatureRespType
     * @throws ICPMException
     */
    @WebMethod(operationName = "SignatureByTemplate")
    @WebResult(name = "SignatureResp", partName = "SignatureResp")
    public SignatureRespType signatureByTemplate(
        @WebParam(name = "SignatureTemplateReq", partName = "SignatureTemplateReq")
        SignatureTemplateReqType signatureTemplateReq)
        throws ICPMException
    ;

    /**
     * 
     * @param simpleSignatureReqType
     * @return
     *     returns br.com.esec.mss.ap.SimpleSignatureRespTypeV4
     * @throws ICPMException
     */
    @WebMethod(operationName = "SimpleSignature")
    @WebResult(name = "SimpleSignatureRespType", partName = "SimpleSignatureRespType")
    public SimpleSignatureRespTypeV4 simpleSignature(
        @WebParam(name = "SimpleSignatureReqType", partName = "SimpleSignatureReqType")
        SimpleSignatureReqTypeV4 simpleSignatureReqType)
        throws ICPMException
    ;

    /**
     * 
     * @param findSignatureReq
     * @return
     *     returns br.com.esec.mss.ap.SignatureStatusRespType
     * @throws ICPMException
     */
    @WebMethod(operationName = "FindSignature")
    @WebResult(name = "SignatureStatusReq", partName = "SignatureStatusReq")
    public SignatureStatusRespType findSignature(
        @WebParam(name = "FindSignatureReq", partName = "FindSignatureReq")
        FindSignatureReqType findSignatureReq)
        throws ICPMException
    ;

    /**
     * 
     * @param signatureStatusReqType
     * @return
     *     returns br.com.esec.mss.ap.BatchSignatureStatusRespType
     * @throws ICPMException
     */
    @WebMethod(operationName = "BatchSignatureStatus")
    @WebResult(name = "BatchSignatureStatusRespType", partName = "BatchSignatureStatusRespType")
    public BatchSignatureStatusRespType batchSignatureStatus(
        @WebParam(name = "SignatureStatusReqType", partName = "SignatureStatusReqType")
        SignatureStatusReqType signatureStatusReqType)
        throws ICPMException
    ;

    /**
     * 
     * @param signatureStatusReq
     * @return
     *     returns br.com.esec.mss.ap.SignatureStatusRespType
     * @throws ICPMException
     */
    @WebMethod(operationName = "StatusQuery")
    @WebResult(name = "SignatureStatusReq", partName = "SignatureStatusReq")
    public SignatureStatusRespType statusQuery(
        @WebParam(name = "SignatureStatusReq", partName = "SignatureStatusReq")
        SignatureStatusReqType signatureStatusReq)
        throws ICPMException
    ;

    /**
     * 
     * @param batchSignatureReqType
     * @return
     *     returns br.com.esec.mss.ap.BatchSignatureRespTypeV2
     * @throws ICPMException
     */
    @WebMethod(operationName = "BatchSignature")
    @WebResult(name = "BatchSignatureRespType", partName = "BatchSignatureRespType")
    public BatchSignatureRespTypeV2 batchSignature(
        @WebParam(name = "BatchSignatureReqType", partName = "BatchSignatureReqType")
        BatchSignatureReqTypeV2 batchSignatureReqType)
        throws ICPMException
    ;

    /**
     * 
     * @param validateReq
     * @return
     *     returns br.com.esec.mss.ap.ValidateRespType
     * @throws ICPMException
     */
    @WebMethod(operationName = "Validate")
    @WebResult(name = "ValidateResp", partName = "ValidateResp")
    public ValidateRespType validate(
        @WebParam(name = "ValidateReq", partName = "ValidateReq")
        ValidateReqType validateReq)
        throws ICPMException
    ;

}
