
package br.com.esec.mss.ap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SignatureService", targetNamespace = "http://esec.com.br/mss/ap", wsdlLocation = "file:/C:/Users/alexr/Temp/wsdl/SignatureEndpointBean.wsdl")
public class SignatureService
    extends Service
{

    private final static URL SIGNATURESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.esec.mss.ap.SignatureService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.esec.mss.ap.SignatureService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/alexr/Temp/wsdl/SignatureEndpointBean.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/alexr/Temp/wsdl/SignatureEndpointBean.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SIGNATURESERVICE_WSDL_LOCATION = url;
    }

    public SignatureService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SignatureService() {
        super(SIGNATURESERVICE_WSDL_LOCATION, new QName("http://esec.com.br/mss/ap", "SignatureService"));
    }

    /**
     * 
     * @return
     *     returns SignaturePortType
     */
    @WebEndpoint(name = "SignaturePortType")
    public SignaturePortType getSignaturePortType() {
        return super.getPort(new QName("http://esec.com.br/mss/ap", "SignaturePortType"), SignaturePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SignaturePortType
     */
    @WebEndpoint(name = "SignaturePortType")
    public SignaturePortType getSignaturePortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://esec.com.br/mss/ap", "SignaturePortType"), SignaturePortType.class, features);
    }

}
